name: wshop
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+40

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  path_provider: ^1.4.0
  flutter_downloader: ^1.3.3
  permission_handler: ^3.3.0
  package_info: ^0.4.0+10
  in_app_purchase: ^0.2.2+1
  image_picker: ^0.6.1+4
  flutter_webview_plugin: ^0.3.8
  webview_flutter: ^0.3.14+1
  multi_image_picker: ^4.5.6
  cached_network_image: ^1.1.1
  carousel_slider: ^1.3.1
  shared_preferences: ^0.5.3+4
  sqflite: ^1.1.6+3
  flutter_pagewise: ^1.2.3
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  rxdart: ^0.21.0
  flutter_image_compress: ^0.6.3
  qr_flutter: ^3.0.1
  dio: ^3.0.4
  fluwx: ^1.1.3
  uuid: ^2.0.2
  oktoast: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/header.png
    - assets/timeline.png
    - assets/timeline_active.png
    - assets/fav.png
    - assets/fav_active.png
    - assets/mine.png
    - assets/mine_active.png
    - assets/share.png
    - assets/bg.png
    - assets/login_bg_top.png
    - assets/login_bg_middle.png
    - assets/login_btn_icon_1.png
    - assets/login_btn_icon_2.png
    - assets/wechat_icon.png
    - assets/star.png
    - assets/qrcode.png
    - assets/banner.png
    - assets/not_vip.png
    - assets/invite.png
    - assets/money.png
    - assets/setting.png
    - assets/contact.png
    - assets/stared.png
    - assets/price_bg.png
    - assets/user_intro_bg.png
    - assets/withdraw_icon.png
    - assets/success_icon.png
    - assets/aqy.jpg
    - assets/tx.jpg
    - assets/mg.jpg
    - assets/yk.jpg
    - assets/js/test.js


  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/bg.png
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
